# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: HASNAT ABDULLAH
site_description: Senior Software Engineer(Backend, django, AI, ML, LLM, Database, Timeseries, ETL), Researcher
site_url: https://hasnat-abdullah.github.io

theme:
  name: material
  icon:
    logo: simple/codechef
  favicon: assets/images/favicon.png

  font:
    text: Roboto Mono
    code: Roboto Mono

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.boost
    - header.autohide
    - content.footnote.tooltips

plugins:
  - search
#  - social
  - blog:
      post_url_format: "{categories}/{slug}"
      archive: false
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
#  - meta
#  - optimize
  - offline
#  - typeset

extra:
  generator: false # hide The footer displays a Made with Material for MkDocs notice
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hasnat-abdullah
  analytics:
    provider: google
    property: G-W2KTXPTZKD

copyright: Copyright &copy; 2025 Hasnat Abdullah

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - assets/css/custom.css

nav:
  - HOME: index.md
  - PORTFOLIO: portfolio.md
  - PUBLICATIONS: publications.md
  - BLOG:
      - blog/index.md
